#!/usr/bin/python
from datetime import datetime
import glob, getpass, os, subprocess, shutil

def switch(should_unlock):
  in_dir = 'decrypted'
  out_dir = 'encrypted'

  if should_unlock:
    in_dir, out_dir = out_dir, in_dir

  if not os.path.exists(out_dir):
    os.mkdir(out_dir)

  if not os.path.exists(in_dir):
    os.mkdir(in_dir)

  for in_path in glob.glob('{}/*.*'.format(in_dir)):
    out_path = in_path.replace(in_dir, out_dir, 1)

    print 'in_path:', in_path
    print 'out_path:', out_path

    encrypt_command = [
      'openssl', 'enc', '-in', in_path, '-out', out_path, '-{}'.format(out_dir[0]), '-aes256',
      '-pass', 'pass:{}'.format(PASSWORD)
    ]
    subprocess.call(encrypt_command)

PASSWORD = getpass.getpass('Enter hash password:')

switch(True)
print 'files decrypted, press return to reencrypt'
raw_input()
switch(False)
shutil.rmtree('decrypted')
